spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

logging:
  level:
    org:
      springframework.jdbc: DEBUG                       #jdbcTemplate sql log
      hibernate.sql: DEBUG # Hibernate가 생성하고 실행하는 SQL
      hibernate.type.descriptor.sql.BasicBinder: TRACE  # SQL에 바인딩 되는 파라미터 확인 가능
    hello.itemservice.repository.mybatis: trace         # MyBatis sql log

# MyBatis
mybatis:
  type-aliases-package: hello.itemservice.domain
  configuration:
    map-underscore-to-camel-case: true # false가 디폴트

